RVideos/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Create Swagger schema
schema_view = get_schema_view(
    openapi.Info(
        title="RVideos API",
        default_version='v1',
        description="API for RVideos",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    # URLs for Swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('video/<str:name>', views.VideoView.as_view(), name="video"),
    path('channel/<str:name>', views.ChannelView.as_view(), name='channel'),
    path('comment', views.AddCommentView.as_view(), name='comment'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('upload-video', views.UploadVideoView.as_view(), name='upload-video'),
    path('search', views.Search.as_view(), name='search'),
    path('create-channel', views.CreateChannel.as_view(), name='create-channel'),
    path('drop-channel', views.DropChannel.as_view(), name='drop-channel'),
    path('drop-video', views.DropVideo.as_view(), name='drop-video'),
    path('change-video-page/<str:video>', views.ChangeVideoPage.as_view(), name='change-video'),
    path('change-video', views.ChangeVideo.as_view()),
    path('change-channel-page/<str:channel>', views.ChangeChannelPage.as_view(), name='change-channel'),
    path('change-channel', views.ChangeChannel.as_view()),
    path('like', views.LikeVideo.as_view()),
    path('subscribe', views.Subscribe.as_view()),
    path('generate-poster', views.GeneratePoster.as_view(), name='generate-poster'),
    path('', views.IndexView.as_view(), name="index")
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Channel(models.Model):
    """Канал"""
    name = models.CharField("Название канала", max_length=150)
    logo = models.ImageField("Картинка канала", upload_to='channel_images/', null=True)
    description = models.TextField("Описание канала")
    owner = models.ForeignKey(User, verbose_name="Владелец канала", on_delete=models.CASCADE)
    subscribers = models.ManyToManyField(User, verbose_name='Пользователи, подписавшиеся на канал',
                                         related_name='subscribed_users')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Канал"
        verbose_name_plural = "Каналы"


class Category(models.Model):
    """Категории видео"""
    name = models.CharField("Название категории", max_length=150)
    description = models.TextField("Описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Video(models.Model):
    """Видео"""
    name = models.CharField("Название видео", max_length=150, unique=True)
    description = models.TextField("Описание видео")
    likes = models.IntegerField("Кол-во лайков", default=0)
    dislikes = models.IntegerField("Кол-во дизлайков", default=0)
    liked_by = models.ManyToManyField(User, verbose_name="Пользователи, поставившие видео лайк",
                                      related_name='liked_users')
    disliked_by = models.ManyToManyField(User, verbose_name="Пользователи, поставившие видео дизлайк",
                                         related_name='disliked_users')
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    channel = models.ForeignKey(Channel, verbose_name="Канал", on_delete=models.CASCADE)
    video = models.FileField("Видео", upload_to="videos/videos/")
    poster = models.ImageField("Постер", upload_to="videos/posters")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = "Видео"


class Comment(models.Model):
    """Комментарий к видео"""
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    text = models.TextField("Текст")
    video = models.ForeignKey(Video, verbose_name="Видео", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ": " + self.video.name

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

main/views.py
# Импортируем:
import os
# Возможность отправки статуса в качестве ответа
from django.http import HttpResponse
# Тоже формы ответа сервера
from django.shortcuts import render, redirect
# Класс, от которого нужно наследовать view'шки
from django.views import View
# Записи базы данных
from .models import Video, Channel, Comment, Category
from django.contrib.auth.models import User
# Нечёткое сравнение
from fuzzywuzzy import fuzz
# Модуль для получения отдельного кадра из видео
# import cv2
from django.core.files.storage import FileSystemStorage


class IndexView(View):
    """Главная страница"""
    """
    Class for handling the main page of the website.

    This class handles the HTTP GET request and displays the main page, which shows all the videos.

    Methods
    -------
    get(request):
        Handles the HTTP GET request and fetches all the videos to display on the main page.
    """

    @staticmethod
    def get(request):
        videos = Video.objects.all()[::-1]
        return render(request, 'main/index.html', {"videos": videos})

    """
            Handles the HTTP GET request and fetches all the videos to display on the main page.

            Parameters
            ----------
            request : django.http.HttpRequest
                The HTTP GET request sent by the client.

            Returns
            -------
            django.http.HttpResponse
                The HTTP response containing the main page with all the videos.
    """


class VideoView(View):
    """Страница определённого видео"""

    @staticmethod
    def get(request, name):
        reaction = 'none'
        video = Video.objects.get(name=name)
        if request.user.is_authenticated:
            try:
                video.liked_by.get(username=request.user.username)
                reaction = 'like'
            except:
                try:
                    video.disliked_by.get(username=request.user.username)
                    reaction = 'dislike'
                except:
                    reaction = 'none'
        return render(request, 'main/video.html', {"video": video, "reaction": reaction})


class ChannelView(View):
    """Страница канала"""

    @staticmethod
    def get(request, name):
        # Получаем объект канала
        channel = Channel.objects.get(name=name)
        # Получаем общее кол-во видео
        count = len(channel.video_set.all())
        # Получаем все доступные категории (необходимо для работы формы загрузки видео внизу страницы канала)
        categories = Category.objects.all()
        return render(request, 'main/channel.html', {"channel": channel, "count": count, "categories": categories})


class AddCommentView(View):
    """Добавление комментария к видео"""

    @staticmethod
    def post(request):
        # Начинаем готовить ответ
        response = HttpResponse()
        # Небольшая защита (долго писать от чего)
        try:
            # Получаем объект пользователя из базы данных
            user = User.objects.get(username=request.user.username)
            # Получаем объект видео
            video_name = request.POST.get("video")
            video = Video.objects.get(name=video_name)
            # Получаем текст будущего комментария
            text = request.POST.get("text")
            # Создаём запись о существовании комментария в базе данных
            comment = Comment.objects.create(
                user=user,
                video=video,
                text=text
            )
            comment.save()
            # Записываем информацию об успешном выполнении запроса
            response.status_code = 200
        except:
            response.status_code = 404
        # Возвращаем статус
        return response


class ProfileView(View):
    """Профиль(личный кабинет) пользователя"""

    @staticmethod
    def get(request):
        # Смотрим, вошёл ли пользователь и пропускаем только вошедших, иначе отправляем на страницу входа
        if request.user.is_authenticated:
            # Получаем список каналов, владельцем которых является пользователь
            try:
                channel_list = Channel.objects.filter(
                    owner__username=request.user.username)
                are_channels = True
            except:
                print("no channels")
                channel_list = []
                are_channels = False
            # Возвращаем результат
            return render(request, 'main/profile.html', {"channel_list": channel_list, "are_channels": are_channels})
        else:
            return redirect('/accounts/login')


class UploadVideoView(View):
    """Загрузка на сайт нового видео"""

    @staticmethod
    def post(request):
        # Создаём объект ответа
        response = HttpResponse()
        # Получаем данные из запроса и из базы данных
        name = request.POST.get('name')
        description = request.POST.get('description')
        video = request.FILES.get('video')
        category_name = request.POST.get('category')
        category = Category.objects.get(name=category_name)
        channel_name = request.POST.get('channel')
        poster = request.FILES.get('poster')
        channel = Channel.objects.get(name=channel_name)
        # Создаём запись о видео в базе данных
        new_video = Video.objects.create(
            name=name,
            description=description,
            video=video,
            poster=poster,
            category=category,
            channel=channel
        )
        new_video.save()
        response.status_code = 200
        # Возвращаем ответ
        return response


class Search(View):
    """Поиск по сайту"""

    @staticmethod
    def get(request):
        # Получаем текст поиска
        request_text = request.GET.get('request_text')
        # Получаем видео
        videos = Video.objects.all()
        # Объявляем массив подходящих видео
        correct_videos = []
        # Обрабатываем массив видео
        for video in videos:
            # Альтернативная версия условия поиска
            # if (fuzz.ratio(video.name.lower(), request_text.lower()) > 45) or (fuzz.ratio(request_text.lower(),
            # video.description.lower()) > 45):

            # Если найдено нужное кол-во совпадений запроса и названиявидео считаем его подходящим
            if fuzz.ratio(video.name.lower(), request_text.lower()) > 45:
                correct_videos += [video]
        # Возвращаем ответ
        return render(request, 'main/search.html', {"correct_videos": correct_videos})


class CreateChannel(View):
    """Создание канала"""

    @staticmethod
    def get(request):
        """Страница с формой для заполнения"""
        return render(request, 'main/create-channel.html', {})

    @staticmethod
    def post(request):
        """Непосредственно создание канала"""

        # Проверяем, вошёл ли пользователь
        if request.user.is_authenticated:
            # Получаем данные из запроса
            name = request.POST.get("name")
            description = request.POST.get("description")
            owner = User.objects.get(username=request.user.username)
            logo = request.FILES.get('logo')
            # Создаём канал
            new_channel = Channel.objects.create(
                name=name,
                description=description,
                owner=owner,
                logo=logo
            )
            new_channel.save()
            # Возвращаем ответ
            response = HttpResponse()
            response.status_code = 200
            return response
        else:
            return redirect("/accounts/login")


class DropChannel(View):
    """Удаление канала"""

    @staticmethod
    def post(request):
        # Проверяем, вошёл ли пользователь
        if request.user.is_authenticated:
            # Получаем введённо имя канала
            channel_name = request.POST.get('channel-name')
            # Начинаем готовить ответ пользователю
            response = HttpResponse()
            # Пробуем получить объект базы данных
            try:
                channel = Channel.objects.get(name=channel_name)
            except:
                # Если не получается, значит введено неверное имя канала
                response.status_code = 405
                return response
            # Проверяем, является ли пользователь владельцем канала
            if request.user.username == channel.owner.username:
                # Удаляем объект
                channel.delete()
                response.status_code = 200
                return response
            else:
                response.status_code = 405
                return response
        else:
            return redirect('/accounts/login')


class DropVideo(View):
    """Удаление видео"""

    @staticmethod
    def post(request):
        # Проверяем, вошёл ли пользователь
        if request.user.is_authenticated:
            # Получаем введённо имя видео
            video_name = request.POST.get('video-name')
            # Начинаем готовить ответ пользователю
            response = HttpResponse()
            # Пробуем получить объект базы данных
            try:
                video = Video.objects.get(name=video_name)
            except:
                # Если не получается, значит введено неверное имя канала
                response.status_code = 405
                return response
            # Проверяем, является ли пользователь владельцем канала, на котором рамещено видео
            if request.user.username == video.channel.owner.username:
                # Удаляем объект
                video.delete()
                response.status_code = 200
                return response
            else:
                response.status_code = 405
                return response
        else:
            return redirect('/accounts/login')


class ChangeVideoPage(View):
    """Страница изменения видео"""

    @staticmethod
    def get(request, video):
        # Пробуем получить видео
        try:

templates/main/change-channel.html
{% extends 'base.html' %}
{% load header %}
{% load static %}

{% block title %}
    Изменить канал: {{ channel.name }}
{% endblock title %}

{% block content %}
    {% get_header 'change-video' %}
    <div class="container">
        <form id="change-channel-form" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">Название</label>
                <input type="text" class="form-control" id="name" name="name" autocomplete="off"
                       value="{{ channel.name }}">
            </div>
            <div class="form-group">
                <label for="poster">Аватар</label>
                <input type="file" name="poster" class="form-control-file" id="poster"
                       accept="image/jpeg,image/jpg,image/png,image/gif">
            </div>
            <div class="form-group">
                <label for="description">Описание</label>
                <textarea name="description" id="description" rows="10"
                          class="form-control">{{ channel.description }}</textarea>
                {% csrf_token %}
                <input type="hidden" value="{{ channel.id }}" name="id">
            </div>
            <input type="submit" class="btn btn-outline-success mb-2" value="Сохранить изменения">
            <a href="{% url 'channel' channel.name %}" class="btn btn-outline-success mb-2" id="link">Перейти на страницу канала</a>
        </form>
    </div>
    <script src="{% static 'js/change-channel_script.js' %}"></script>
{% endblock content %}

templates/main/change-video.html
{% extends 'base.html' %}
{% load header %}
{% load static %}

{% block title %}
    Изменить видео: {{ video.name }}
{% endblock title %}

{% block content %}
    {% get_header 'change-video' %}
    <div class="container">
        <form id="change-video-form" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">Название</label>
                <input type="text" class="form-control" id="name" name="name" autocomplete="off"
                       value="{{ video.name }}">
            </div>
            <div class="form-group">
                <label for="video">Видео</label>
                <input type="file" name="video" class="form-control-file" id="video" accept="video/mp4">
            </div>
            <div class="form-group">
                <label for="poster">Постер</label>
                <input type="file" name="poster" class="form-control-file" id="poster"
                       accept="image/jpeg,image/jpg,image/png,image/gif">
            </div>
            <div class="form-group">
                <label for="category">Категория</label>
                <select class="form-control" name="category" id="category">
                    {% for category in categories %}
                        <option {% if category.name == video.category.name %}selected="selected"{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="description">Описание</label>
                <textarea name="description" id="description" rows="10"
                          class="form-control">{{ video.description }}</textarea>
                {% csrf_token %}
                <input type="hidden" value="{{ video.id }}" name="id">
            </div>
            <input type="submit" class="btn btn-outline-success mb-2" value="Сохранить изменения">
            <a href="{% url 'video' video.name %}" class="btn btn-outline-success mb-2" id="link">Перейти на страницу видео</a>
        </form>
    </div>
    <script src="{% static 'js/change-video_script.js' %}"></script>
{% endblock content %}

templates/main/channel.html
<!-- Страница канала -->

{% extends 'base.html' %}
{% load header %}
{% load cards %}
{% load static %}

{% block title %}
    {{ channel.name }}
{% endblock title %}

{% block content %}
    {% get_header 'channel' %}
    <div class="container text-center">
        <p class="h1 user-select-all"><img src="{{ channel.logo.url }}" style="border-radius: 50%" width="70px"
                                           alt="Логотип канала">{{ channel.name }}</p>
    </div>
    <hr>
    <div class="container">
        {{ channel.description }}
        <p class="mt-2">
            Владелец:
            <mark>{{ channel.owner.username }}</mark>
        </p>
        <p class="mt-2">
            Общее количество видео:
            <mark>{{ count }}</mark>
        </p>
        <p class="mt-2">
            Подписчики:
            <mark>{{ channel.subscribers.count }}</mark>
        </p>
        <input type="button" class="btn btn-outline-success mt-2" onclick="subscribe(`{{ channel.name }}`)"
               value='Подписаться на канал "{{ channel.name }}"'>
    </div>
    <hr>
    <div class="container">
        <p class="h3">
            Все видео:
        </p>
        {% cards channel.video_set.all %}
    </div>
    <hr>
    {% if channel.owner.username == request.user.username %}
        <div class="container mb-3">
            <p class="h3">
                Загрузить видео
            </p>
            <form id="video-form" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" class="form-control" id="name" name="name" autocomplete="off" required>
                </div>
                <div class="form-group">
                    <label for="video">Видео</label>
                    <input type="file" name="video" class="form-control-file" id="video" accept="video/mp4" required>
                </div>
                <div class="form-group">
                    <label for="poster">Постер</label>
                    <input type="file" name="poster" class="form-control-file" id="poster"
                           accept="image/jpeg,image/jpg,image/png,image/gif">
                </div>
                <div class="form-group">
                    <label for="category">Категория</label>
                    <select class="form-control" name="category" id="category">
                        {% for category in categories %}
                            <option value="{{ category.name }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="description">Описание</label>
                    <textarea name="description" id="description" rows="10" class="form-control" required></textarea>
                    {% csrf_token %}
                </div>
                <input type="hidden" value="{{ channel.name }}" name="channel">
                <input type="submit" class="btn btn-outline-success" value="Загрузить">
            </form>
            <button class="btn btn-outline-danger mt-2" data-toggle="modal" data-target="#dropChannelModal">
                Удалить канал
            </button>
            <a href="{% url 'change-channel' channel.name %}" class="btn btn-outline-warning mt-2">Изменить канал</a>
        </div>
        <div class="modal fade" id="dropChannelModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Удалить канал</h5>
                    </div>
                    <form id="drop-channel-form" method='post'>
                        <div class="modal-body">
                            <label for="dropChannelName">Введите название канала, чтобы подтвердить, что вы не
                                робот</label>
                            <input type="text" class="form-control" id="dropChannelName" name="channel-name"
                                   autocomplete="off" required>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                            <input type="submit" class="btn btn-primary" value="Удалить">
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
    <script src="{% static 'js/channel_script.js' %}"></script>
    <script src="{% static 'js/subscribe_script.js' %}"></script>
{% endblock content %}

templates/main/create-channel.html
{% extends 'base.html' %}
{% load header %}
{% load static %}

{% block title %}
Создать канал
{% endblock title %}

{% block content %}
{% get_header 'create-channel' %}
<div class="container">
    <form id="create-channel-form" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="channelName" class="form-label">Название канала</label>
            <input type="text" class="form-control" id="channelName" name="name" required>
        </div>
        <div class="mb-3">
            <label for="channelDescription" class="form-label">Описание канала</label>
            <textarea class="form-control" id="channelDescription" rows="5" name="description" required></textarea>
        </div>
        <div class="mb-3">
            <label for="channelLogo" class="form-label">Логотип канала</label>
            <input class="form-control" type="file" accept=".png, .svg, .gif" name="logo" id="channelLogo" required>
        </div>
        <input type="submit" class="btn btn-primary" value="Создать">
        {% csrf_token %}
    </form>
</div>
<script src="{% static 'js/create-channel.js' %}"></script>
{% endblock content %}

templates/main/video.html
{% extends 'base.html' %}
{% load static %}
{% load header %}

{% block title %}
    {{ video.name }}
{% endblock title %}

{% block content %}
    {% get_header 'video' %}
    <div class="container text-center">
        <p class="h1 user-select-all">{{ video.name }}</p>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8" style="text-align: right">
                <video src="{{ video.video.url }}" poster="{{ video.poster.url }}" controls
                       style="width: 100%" class="rounded"></video>
                <div class="row">
                    <div class="col-sm-4 text-center">
                        <svg width="60px" height="60px" onclick="like('like')">
                            <g id="like-icon"
                                    {% if reaction == 'like' %}
                               style="fill: blue"
                                    {% endif %}>
                                <path d="M9.5,43c-2.757,0-5,2.243-5,5s2.243,5,5,5s5-2.243,5-5S12.257,43,9.5,43z"></path>
                                <path d="M56.5,35c0-2.495-1.375-3.662-2.715-4.233C54.835,29.85,55.5,28.501,55.5,27c0-2.757-2.243-5-5-5H36.134l0.729-3.41
                                c0.973-4.549,0.334-9.716,0.116-11.191C36.461,3.906,33.372,0,30.013,0h-0.239C28.178,0,25.5,0.909,25.5,7c0,14.821-6.687,15-7,15
                                h0h-1v-2h-16v38h16v-2h28c2.757,0,5-2.243,5-5c0-1.164-0.4-2.236-1.069-3.087C51.745,47.476,53.5,45.439,53.5,43
                                c0-1.164-0.4-2.236-1.069-3.087C54.745,39.476,56.5,37.439,56.5,35z M3.5,56V22h12v34H3.5z"></path>
                            </g>
                        </svg>
                        <mark id="like-counter">{{ video.likes }}</mark>
                        <svg width="60px" height="60px" onclick="like('dislike')">
                            <g id="dislike-icon"
                                    {% if reaction == 'dislike' %}
                               style="fill: blue"
                                    {% endif %}>
                                <path d="M40.5,0v2h-28c-2.757,0-5,2.243-5,5c0,1.164,0.4,2.236,1.069,3.087C6.255,10.524,4.5,12.561,4.5,15
                                    c0,1.164,0.4,2.236,1.069,3.087C3.255,18.524,1.5,20.561,1.5,23c0,2.495,1.375,3.662,2.715,4.233C3.165,28.15,2.5,29.499,2.5,31
                                    c0,2.757,2.243,5,5,5h14.366l-0.729,3.41c-0.973,4.551-0.334,9.717-0.116,11.191C21.539,54.094,24.628,58,27.987,58h0.239
                                    c1.596,0,4.274-0.909,4.274-7c0-14.82,6.686-15,7-15h0h1v2h16V0H40.5z M54.5,36h-12V2h12V36z"></path>
                                <path d="M48.5,15c2.757,0,5-2.243,5-5s-2.243-5-5-5s-5,2.243-5,5S45.743,15,48.5,15z"></path>
                            </g>
                        </svg>
                        <mark id="dislike-counter">{{ video.dislikes }}</mark>
                    </div>
                    <div class="col-sm-4 text-center">
                        <p class="h4">
                            <a href="{% url 'channel' video.channel.name %}">
                                <img src="{{ video.channel.logo.url }}" style="border-radius: 50%" width="50px"
                                     alt="Логотип канала">
                                {{ video.channel.name }}
                            </a>
                        </p>
                    </div>
                </div>

                {% if video.channel.owner.username == request.user.username %}
                    <button class="btn btn-outline-danger mt-2" data-toggle="modal" data-target="#dropVideoModal">
                        Удалить видео
                    </button>
                    <a href="{% url 'change-video' video.name %}" class="btn btn-outline-warning mt-2">Изменить
                        видео</a>
                {% endif %}
                <input type="button" class="btn btn-outline-success mt-2"
                       onclick="subscribe(`{{ video.channel.name }}`)"
                       value='Подписаться на канал "{{ video.channel.name }}"'>
            </div>
            <div class="col-md mt-2">
                <p class="h6 border border-secondary" style="padding: 10px">
                    {{ video.description }}
                </p>
                <p class="h5">Категория: {{ video.category.name }}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="container" id="comments_set">
        {% for comment in video.comment_set.all %}
            <div>
                <h5 class="mt-0">{{ comment.user.username }}</h5>
                {{ comment.text }}
                <hr>
            </div>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
        <div class="container">
            <form id="comment_form">
                <div class="form-group">
                    <p class="h3">Оставьте комментарий:</p>
                    <label for="commentText">Текст комментария</label>
                    <textarea name="text" class="form-control" id="commentText" rows="10"></textarea>
                    <input type="hidden" name="video" value="{{ video.name }}">
                    {% csrf_token %}
                </div>
                <input type="submit" class="btn btn-outline-success" value="Отправить">
            </form>
        </div>
    {% else %}
        <div class="container">
            <p class="h5"><a href="{% url 'account_signup' %}">Зарегестрируйтесь</a>, чтобы оставить комментарий.</p>
        </div>
    {% endif %}
    <hr>
    {% if video.channel.owner.username == request.user.username %}
        <div class="modal fade" id="dropVideoModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Удалить видео</h5>
                    </div>
                    <form id="drop-video-form" method='post'>
                        <div class="modal-body">
                            <label for="dropVideoName">Введите название видео, чтобы подтвердить, что вы не
                                робот</label>
                            <input type="text" class="form-control" id="dropVideoName" name="video-name"
                                   autocomplete="off" required>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                            <input type="submit" class="btn btn-primary" value="Удалить">
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
    <script src="{% static 'js/video_script.js' %}"></script>
    <script src="{% static 'js/subscribe_script.js' %}"></script>
    <input type="hidden" value="{{ request.user.username }}" id="username">
    <input type="hidden" value="{{ video.name }}" id="hidden-name">
{% endblock content %}